osx_image: xcode12.4
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.6.6
before_install:
  - gem update cocoapods
  - gem install bundler
  - bundle install
  - gem install xcpretty

script: ./test.sh
